# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule:
    - cron: "0 * * * *"
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    # permissions:
      # contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          #  - public_repo
          #  - repo
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: bartoligerman497
          config_timezone: America/Buenos_Aires
          template: classic
          # committer_message: "chore: update metrics"

          # Stats
          # base: ""
          base: header, metadata
          base_hireable: yes
          config_octicon: yes
          config_twemoji: yes
          
          # Languages
          commits_authoring: German Bartoli, bartoligerman497, bartoligerman497@users.noreply.github.com          
          plugin_languages: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_categories: markup, programming, prose, data
          plugin_languages_colors: github
          plugin_languages_ignored: Rich Text Format, JSON, XML, TEXT, INI, Ant Build System, Microsoft Visual Studio Solution, JAR Manifest, SVG
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          # plugin_languages_recent_days: 14
          # plugin_languages_recent_load: 300
          plugin_languages_sections: most-used, recently-used
          # plugin_languages_threshold: 0%d
          plugin_languages_indepth: yes

          # Waka
          plugin_wakatime: yes
          plugin_wakatime_user: bartoligerman497
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, editors-graphs, os, os-graphs
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_languages_other: yes
          plugin_wakatime_languages_ignored: Other
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}

          # plugin_wakatime: yes
          # plugin_wakatime_url: https://wakatime.com
          # plugin_wakatime_user: bartoligerman497
          # plugin_wakatime_days: 365
          # plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}

          # plugin_wakatime_languages_other: yes
          # plugin_wakatime_limit: 5
          # plugin_wakatime_repositories_visibility: all
          # plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
