name: Recently played games
on:
  # Schedule updates (each hour)
  schedule:
    #- cron: "0 0 * * *" # cada hora
    - cron: 0 */6 * * * # cada 6 horas    
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    # permissions:
      # contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
            filename: metrics.plugin.steam.svg
            token: NOT_NEEDED
            base: ""
            plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
            plugin_steam: yes
            plugin_steam_user: "76561198096304489"
            plugin_steam_sections: recently-played
            plugin_steam_achievements_limit: 0
